### Time series MLP, ref: pag.62 Brownlee

In [1]:
conda install tensorflow-gpu

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [3]:
# multivariate mlp example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import Dense
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)

    return array(X), array(y)


Using TensorFlow backend.


### Input data:

In [4]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95, 105, 115, 125, 135, 145])

In [5]:
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
dataset

array([[ 10,  15,  25],
       [ 20,  25,  45],
       [ 30,  35,  65],
       [ 40,  45,  85],
       [ 50,  55, 105],
       [ 60,  65, 125],
       [ 70,  75, 145],
       [ 80,  85, 165],
       [ 90,  95, 185],
       [100, 105, 205],
       [110, 115, 225],
       [120, 125, 245],
       [130, 135, 265],
       [140, 145, 285]])

In [6]:
import pandas as pd

pd.DataFrame(dataset[:5])

0   1    2
0  10  15   25
1  20  25   45
2  30  35   65
3  40  45   85
4  50  55  105

In [7]:
# choose a number of time steps
n_steps = 3
# convert into input/output
X, y = split_sequences(dataset, n_steps)
print('training X: {}'.format(X[:3]))
print('training y: {}'.format(y[:3]))

training X: [[[10 15]
  [20 25]
  [30 35]]

 [[20 25]
  [30 35]
  [40 45]]

 [[30 35]
  [40 45]
  [50 55]]]
training y: [ 65  85 105]


In [8]:
# flatten input
n_input = X.shape[1] * X.shape[2]
X = X.reshape((X.shape[0], n_input))
X[:3]

array([[10, 15, 20, 25, 30, 35],
       [20, 25, 30, 35, 40, 45],
       [30, 35, 40, 45, 50, 55]])

### Model definition

In [9]:
# define model
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=n_input))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [10]:
# https://keras.io/visualization/

from IPython.display import SVG
from keras.utils.visualize_util import model_to_dot

SVG(model_to_dot(model).create(prog='dot', format='svg'))

ModuleNotFoundError: No module named 'keras.utils.visualize_util'

In [12]:
# fit model
model.fit(X, y, epochs=2000, verbose=0)
# demonstrate prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape((1, n_input))
yhat = model.predict(x_input, verbose=0)

print(yhat)









[[205.0016]]


pip install --upgrade tensorflow==2.0.0-rc1

In [11]:
pip install --upgrade tensorflow==2.0.0-rc1

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0-rc1 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.0.0-rc1
